language: clojure
env:
  global:
    - OBB_SCENARIOS_TO_TEST=10
lein: lein2
script: lein test && lein with-profile cljs cljsbuild test
jdk:
  - oraclejdk8
after_script:
  - bash -ex script/coveralls.sh
